version: "3.6"

services:
  frontend:
    build: ./ca
    restart: on-failure
    ports:
    - ${APP_FRONTEND_PORT:-80}:80/tcp
    environment:
      CA_DB_HOST: ${MYSQL_DB_HOST:-mysql}
      CA_DB_USER: ${MYSQL_DB_USER:-user}
      CA_DB_PASSWORD_FILE: /run/secrets/db_pass
      CA_DB_DATABASE: ${MYSQL_DB_NAME:-db}
      CA_APP_DISPLAY_NAME: ${CA_APP_DISPLAY_NAME:-My First Collective Access}
      CA_ADMIN_EMAIL: ${CA_APP_ADMIN_EMAIL:-test@email.com}
      APP_PHP_DEBUG_MODE: ${PHP_DEBUG_MODE:-0}
      APP_PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-64M}
      APP_PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-64M}
      APP_PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
    secrets:
    - source: db_pass
      uid: '0'
      gid: '0'
      mode: 0440

secrets:
  db_pass:
    file: ./secrets/db_pass.txt
  db_root_pass:
    file: ./secrets/db_root_pass.txt
