version: "3.12"

services:
  frontend:
    build: ./ca
    restart: on-failure
    ports:
    - ${APP_FRONTEND_PORT:-80}:80/tcp
    environment:
      CA_DB_HOST: mysql
      CA_DB_USER: user
      CA_DB_PASSWORD: pass
      CA_DB_DATABASE: db
      CA_APP_DISPLAY_NAME: My First CollectiveAccess System
      CA_ADMIN_EMAIL: test@email.com
      APP_PHP_DEBUG_MODE: 0
      APP_PHP_UPLOAD_MAX_FILESIZE: 64M
      APP_PHP_POST_MAX_SIZE: 64M
      APP_PHP_MEMORY_LIMIT: 512M
    volumes:
    - ca_conf:/var/www/html/providence/app/conf/
    - ca_media:/var/www/html/providence/media/
    - ca_logs:/var/www/html/providence/app/log/
    depends_on:
    - mysql

  mysql:
    image: mysql:8.0.28
    restart: always
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
    - ${APP_ADMINER_PORT:-8080}:8080/tcp

volumes:
  ca_conf: {}
  ca_media: {}
  ca_logs: {}
  db_data: {}
